[package]
name = "zombie"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8.1"
once_cell = "1.16.0"
serde = "1.0.147"
serde_json = "1.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
